#application.yml

server:
  port: 8088
  servlet:
      context-path: /aifangyang
spring:
  datasource:
    name: core
    url: jdbc:mysql://192.168.2.87:3306/core
    username: aifangyang
    password: root123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
springfox:
  documentation:
    swagger:
      v2:
        host: localhost:8088
